### ISSUE TITLE
Missing required input `command-windows`

### ISSUE THREAD

**Issue by cornshuckin2** [BerniWittmann/background-server-action#138]
When using this plugin https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-github-actions I receive an error in the `with` block which says `Missing required input `command-windows`

My workflow does not require this yet it is required. This is a minor inconvenience but I always have to double check that my workflow isn't broken.

**Comment by BerniWittmann** [comment]
you're right, it is set as required in the workflow config, although it doesn't have to be. Will post a fix shortly

**Comment by BerniWittmann** [comment]
@cornshuckin2 Just released  a new version [v1.1.1](https://github.com/BerniWittmann/background-server-action/releases/tag/v1.1.1) with this fix. 

If you use the action as follows `uses: BerniWittmann/background-server-action@v1` you should automatically get the new update :) thanks for letting me know :)
